synapse_project:
  target: dev
  outputs:
    dev:
      type: synapse
      authentication: cli
      driver: ODBC Driver 18 for SQL Server
      server: synapsewsshijin.sql.azuresynapse.net
      database: lake_db
      schema: dbo
      encrypt: true
      trust_cert: false