version: 2

sources:
  - name: lake_db
    description: "This is the source schema for the lake database."
    database: dedicated_synapsepool
    schema: dbo
    tables:
      - name: customers
        description: "This table contains external customers data."


